# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch

# Create random tensor
my_tensor = torch.rand(7, 7)
my_tensor

tensor([[0.9382, 0.4177, 0.9950, 0.6378, 0.6625, 0.1734, 0.3179],
        [0.9523, 0.7592, 0.5407, 0.4456, 0.1399, 0.6089, 0.8376],
        [0.6219, 0.2193, 0.5763, 0.4459, 0.4417, 0.0170, 0.9636],
        [0.5547, 0.7977, 0.1899, 0.6492, 0.3040, 0.8998, 0.0864],
        [0.8368, 0.7485, 0.1702, 0.8747, 0.3933, 0.0301, 0.3074],
        [0.5724, 0.2563, 0.7536, 0.1271, 0.6257, 0.5342, 0.3609],
        [0.7187, 0.4393, 0.1770, 0.8595, 0.3844, 0.2745, 0.2623]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [2]:
# Create another random tensor
tensor_2 = torch.rand(1, 7)

# Perform matrix multiplication
my_tensor.mm(tensor_2.T)

tensor([[1.9921],
        [2.6348],
        [1.9540],
        [1.9357],
        [1.8853],
        [1.5184],
        [1.7525]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [3]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor_1 = torch.rand(7, 7)
tensor_2 = torch.rand(1, 7)

# Matrix multiply tensors
mm_tensor = tensor_1.mm(tensor_2.T)

print(f"({mm_tensor}, {mm_tensor.shape}")

(tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]), torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [5]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [14]:
# Set random seed on the GPU
torch.cuda.manual_seed(0)

tensor_1 = torch.rand(7, 7, device='cuda:0')
tensor_2 = torch.rand(1, 7, device='cuda:0')

mm_tensor = tensor_1.mm(tensor_2.T)

print(f"({mm_tensor}, {mm_tensor.shape})")

(tensor([[2.0534],
        [2.3578],
        [1.8793],
        [1.6912],
        [2.5042],
        [2.0659],
        [1.9022]], device='cuda:0'), torch.Size([7, 1]))



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [32]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"

# Create two random tensors on GPU
tensor_1 = torch.rand(2, 3).to(device)
tensor_2 = torch.rand(2, 3).to(device)

print(f"Device: {device}")
print(f"({tensor_1},\n {tensor_2})")


Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0'))



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [33]:
# Perform matmul on tensor_A and tensor_B
mm_tensor = tensor_1.matmul(tensor_2.T)

print(f"({mm_tensor}, {mm_tensor.shape})")

(tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))


### 8. Find the maximum and minimum values of the output of 7.

In [34]:
# Find max
print(f"MAX: {torch.max(mm_tensor)}, {mm_tensor.max()}")

# Find min
print(f'MIN: {torch.min(mm_tensor)}, {mm_tensor.min()}')

MAX: 0.5617256760597229, 0.5617256760597229
MIN: 0.3647301495075226, 0.3647301495075226


### 9. Find the maximum and minimum index values of the output of 7.

In [36]:
# Find arg max
arg_max = torch.argmax(mm_tensor)

# Find arg min
arg_min = torch.argmin(mm_tensor)

arg_max, arg_min


(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [31]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_A = torch.rand(1, 1, 1, 10)

# Remove single dimensions
tensor_B = tensor_A.squeeze()

# Print out tensors and their shapes
print(f"({tensor_A}, {tensor_A.shape})")
print(f"({tensor_B}, {tensor_B.shape})")


(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]), torch.Size([1, 1, 1, 10]))
(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]), torch.Size([10]))
